### PR TITLE
feat(COMPASS-4530): Increase default max time ms to 1 minute

### PR DESCRIPTION
**Pull request by gribnoysup**
Changed the default value so that when Compass passes an empty string to the validation method it returns 1 minute

Part of https://jira.mongodb.org/browse/COMPASS-4530

### CODE REVIEW

**Review by addaleax — APPROVED** [review]

**Review by mcasimir — APPROVED** [review]
Nice!

**Review by Anemy — APPROVED** [review]
Looks good. Small thing, how do you feel about removing the `ms` package? (fine to leave it as is)
Since we only use it for this one command we could also do
```javascript
const DEFAULT_MAX_TIME_MS = 60000; // 1 minute.
```

**Comment by gribnoysup** [comment]
Yeah, definitely, that's a good point, I'll remove it 👍

**Review by Anemy — APPROVED** [review]
:shipit:

**Pull request merged**
